QLKS/Controllers/BookingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QLKS.Controllers
{
    public class BookingController : Controller
    {
        // GET: Booking
        public ActionResult Index()
        {
            return View();
        }
    }
}

QLKS/Controllers/GalleryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QLKS.Controllers
{
    public class GalleryController : Controller
    {
        // GET: Gallery
        public ActionResult Index()
        {
            return View();
        }
    }
}

QLKS/Controllers/RestaurantController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QLKS.Controllers
{
    public class RestaurantController : Controller
    {
        // GET: Restaurant
        public ActionResult Index()
        {
            return View();
        }
    }
}

QLKS/Controllers/ServiceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using QLKS.Models.Entities;

namespace QLKS.Controllers
{
    public class ServiceController : Controller
    {
        Models.EF.QLKS qlks = new Models.EF.QLKS();
        // GET: Service
        public ActionResult Index()
        {
            List<tLoaiPhong> _list = new List<tLoaiPhong>();
            _list = qlks.tLoaiPhong.ToList();
            return View(_list);
        }
    }
}

QLKS/Controllers/TestimonialController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QLKS.Controllers
{
    public class TestimonialController : Controller
    {
        // GET: Testimonial
        public ActionResult Index()
        {
            return View();
        }
    }
}

QLKS/Views/Restaurant/Index.cshtml
@{
    ViewBag.Title = "Index";
    ViewBag.Page = "page4";
}

<div id="header" class="small">
    <div class="row-1">
        <div class="wrapper">
            <div class="logo">
                <h1><a href="#">Five Star</a></h1>
                <em>Hotel</em> <strong>True Luxury</strong>
            </div>
            <div class="phones">
                1-800-412-45-56<br />
                1-800-542-64-48
            </div>
        </div>
    </div>
    <div class="row-2 alt">
        <div class="indent">
            <!-- header-box-small begin -->
            <div class="header-box-small">
                <div class="inner">
                    <ul class="nav">
                        <li><a href="@Url.Action("Index", "Home")" >Trang chủ</a></li>
                        <li><a href="@Url.Action("Index", "Service")">Dịch vụ</a></li>
                        <li><a href="@Url.Action("Index", "Gallery")">Hình ảnh</a></li>
                        <li><a href="@Url.Action("Index", "Restaurant")" class="current">Phòng ăn</a></li>
                        <li><a href="@Url.Action("Index", "Testimonial")">Đánh Giá</a></li>
                        <li><a href="@Url.Action("Index", "Booking")">Đặt phòng</a></li>
                    </ul>
                </div>
            </div>
            <!-- header-box-small end -->
        </div>
    </div>
</div>
<!-- content -->
<div id="content">
    <div class="gallery">
        <ul>
            <li><a href="#"><img alt="" src="~/Content/images/2page-img1.jpg" /></a></li>
            <li><a href="#"><img alt="" src="~/Content/images/2page-img2.jpg" /></a></li>
            <li><a href="#"><img alt="" src="~/Content/images/2page-img3.jpg" /></a></li>
            <li><a href="#"><img alt="" src="~/Content/images/2page-img4.jpg" /></a></li>
            <li><a href="#"><img alt="" src="~/Content/images/2page-img5.jpg" /></a></li>
            <li><a href="#"><img alt="" src="~/Content/images/2page-img6.jpg" /></a></li>
        </ul>                               
    </div>
    <div class="container">
        <div class="aside maxheight">
            <!-- box begin -->
            <div class="box maxheight">
                <div class="inner">
                    <h3>Menu</h3>
                    <ul class="list3">
                        <li><a href="#">Specials</a></li>
                        <li><a href="#">Lunch</a></li>
                        <li><a href="#">Diner</a></li>
                        <li><a href="#">Beverage</a></li>
                        <li><a href="#">Winery</a></li>
                        <li><a href="#">Dessert</a></li>
                        <li><a href="#">Italian</a></li>
                        <li><a href="#">French</a></li>
                        <li><a href="#">German</a></li>
                    </ul>
                    <div class="button"><span><span><a href="#">Make Reservation</a></span></span></div>
                </div>
            </div>
            <!-- box end -->
        </div>
        <div class="content">
            <div class="indent">
                <h2>Today’s featured menu item</h2>
                <img class="img-indent png alt" alt="" src="~/Content/images/4page-img1.png" />
                <div class="extra-wrap">
                    <h5>Foie gras!</h5>
                    <ul class="list2">
                        <li>Nice and tasty!</li>
                        <li>Made from French ingredients!</li>
                        <li>Cooked by Italian chef!</li>
                        <li>Awarded by Czech assosiation of chef!</li>
                        <li>Proved to be good for your health!</li>
                    </ul>
                    <div class="aligncenter"><strong class="txt2">AS LOW AS €19!</strong></div>
                </div>
            </div>
        </div>
        <div class="clear"></div>
    </div>
</div>
<!-- footer -->
<div id="footer">
    <ul class="nav">
        <li><a href="#">Home</a>|</li>
        <li><a href="#">Services</a>|</li>
        <li><a href="#">Gallery</a>|</li>
        <li><a href="#">Restaurant</a>|</li>
        <li><a href="#">Testimonials</a>|</li>
        <li><a href="#">Booking</a></li>
    </ul>
    <div class="wrapper">
        <div class="fleft">Copyright &copy; 2009 <a href="#">Name Here</a>. All Rights Reserved</div>
        <div class="fright">Designed by TemplateMonster - <a href="http://www.templatemonster.com/">website templates</a> provider</div>
    </div>
</div>